name       : opencl-clang
version    : 10.0.0_1
release    : 1
source     :
    - https://github.com/intel/opencl-clang/archive/refs/tags/v10.0.0-1.tar.gz : 815005b6fb7fd8fd2f08b9036035d3aa9543f5ce8464e41ef2f2ed08a816f507
license    : Apache-2.0-with-LLVM-exception
component  : programming.library
homepage   : https://github.com/intel/opencl-clang/
summary    : A thin, OpenCL-oriented wrapper library around clang
description: |
    opencl-clang is a thin wrapper library around clang. The library has an OpenCL-oriented API and is capable to compile OpenCL C kernels to SPIR-V modules.
clang      : yes
builddeps  :
    - pkgconfig(LLVMSPIRVLib)
setup      : |
    %cmake_ninja \
        -DLLVMSPIRV_INCLUDED_IN_LLVM=OFF \
        -DSPIRV_TRANSLATOR_DIR=/usr \
        -Wno-dev
build      : |
    %ninja_build
install    : |
    %ninja_install
