name       : opencl-clang
version    : 13.0.0
release    : 5
source     :
    - https://github.com/intel/opencl-clang/archive/refs/tags/v13.0.0.tar.gz : fea502dadbbe9f15cb6280e4931ad5b88b7df3256a15126e8453294367afd75f
license    : Apache-2.0-with-LLVM-exception
component  : programming.library
homepage   : https://github.com/intel/opencl-clang/
summary    : A thin, OpenCL-oriented wrapper library around clang
description: |
    opencl-clang is a thin wrapper library around clang. The library has an OpenCL-oriented API and is capable to compile OpenCL C kernels to SPIR-V modules.
clang      : yes
builddeps  :
    - pkgconfig(LLVMSPIRVLib)
setup      : |
    %cmake_ninja \
        -DLLVMSPIRV_INCLUDED_IN_LLVM=OFF \
        -DSPIRV_TRANSLATOR_DIR=/usr \
        -DPREFERRED_LLVM_VERSION=$version \
        -Wno-dev
build      : |
    %ninja_build
install    : |
    %ninja_install
