name       : opencl-clang
version    : 14.0.0
release    : 9
source     :
    - git|https://github.com/intel/opencl-clang.git : 704b5a29947fa403f97abb21b5b5a9c34939db5e
license    : Apache-2.0-with-LLVM-exception
component  : programming.library
homepage   : https://github.com/intel/opencl-clang/
summary    : A thin, OpenCL-oriented wrapper library around clang
description: |
    opencl-clang is a thin wrapper library around clang. The library has an OpenCL-oriented API and is capable to compile OpenCL C kernels to SPIR-V modules.
clang      : yes
builddeps  :
    - pkgconfig(LLVMSPIRVLib)
setup      : |
    %cmake_ninja \
        -DLLVMSPIRV_INCLUDED_IN_LLVM=OFF \
        -DSPIRV_TRANSLATOR_DIR=/usr \
        -DPREFERRED_LLVM_VERSION=14.0.6 \
        -Wno-dev
build      : |
    %ninja_build
install    : |
    %ninja_install
