name       : opencl-clang
version    : 11.0.0
release    : 2
source     :
    - https://github.com/intel/opencl-clang/archive/refs/tags/v11.0.0.tar.gz : 0c0d5fb4bfc85c1c1ae4b441eea223193721ecdd3d9165bcc6f7859d90e5bf66
license    : Apache-2.0-with-LLVM-exception
component  : programming.library
homepage   : https://github.com/intel/opencl-clang/
summary    : A thin, OpenCL-oriented wrapper library around clang
description: |
    opencl-clang is a thin wrapper library around clang. The library has an OpenCL-oriented API and is capable to compile OpenCL C kernels to SPIR-V modules.
clang      : yes
builddeps  :
    - pkgconfig(LLVMSPIRVLib)
setup      : |
    %cmake_ninja \
        -DLLVMSPIRV_INCLUDED_IN_LLVM=OFF \
        -DSPIRV_TRANSLATOR_DIR=/usr \
        -DPREFERRED_LLVM_VERSION=11.1.0 \
        -Wno-dev
build      : |
    %ninja_build
install    : |
    %ninja_install
